name: Prettier code formatter

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write
  workflows: write  # Added permission to modify workflows

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Prettier Check 🔎
        id: prettier
        run: npx prettier . --check
      - name: Create and Format diff 📝
        if: ${{ failure() }}
        run: |
          npx prettier . --write
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --cached -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
          git commit -m "Apply Prettier formatting" -a || echo "No changes to commit"
          npm install -g diff2html-cli
          diff2html -i file -s side -F diff.html -- diff.txt
          git push
      - name: Upload html diff ⬆️
        if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: HTML Diff
          path: diff.html
          retention-days: 7
      - name: Dispatch information to repository 🗣️
        if: ${{ failure() && steps.prettier.conclusion == 'failure' && github.event_name == 'pull_request' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: prettier-failed-on-pr
          client-payload: '{"pr_number": "${{ github.event.number }}", "artifact_url": "${{ steps.artifact-upload.outputs.download-url }}", "run_id": "${{ github.run_id }}"}'
